[package]
name = "sanitas_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
env_logger = "0.11.1"
tokio = { version = "1.35.1", features = ["full"] }
tower = "0.4.13"
